SWITCH_WIDTH = 171;
SWITCH_DEPTH = 14;
SWITCH_HEIGHT = 100;

DOCK_SLIT_WIDTH = 8;
DOCK_SLIT_DEPTH = 2;
DOCK_SLIT_HEIGHT = 12;

BACK_HOLE_WIDTH = 42;
BACK_HOLE_HEIGHT = 5;
HOLE_VERTICAL_POSITION = DOCK_SLIT_HEIGHT - BACK_HOLE_HEIGHT;
HOLE_DISTANCE_FROM_CENTER = 4 + DOCK_SLIT_WIDTH / 2;
